// Real AI Tools Data - to replace sample tools in seed.ts
export const realAITools = [
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'Advanced AI chatbot for conversations, writing, coding, and problem-solving',
    longDescription: 'ChatGPT by OpenAI is a powerful conversational AI that can assist with writing, coding, learning, brainstorming, and much more. It understands context and provides human-like responses across various topics.',
    category: 'Content Generation',
    subcategory: 'Chatbot',
    websiteUrl: 'https://chat.openai.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Plus: $20/month',
    features: JSON.stringify(['Natural conversations', 'Code generation', 'Content writing', 'Problem solving', 'Multiple languages']),
    tags: JSON.stringify(['chatbot', 'ai-assistant', 'writing', 'coding']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'AI art generator creating stunning images from text descriptions',
    longDescription: 'Midjourney is an AI image generation tool that creates highly detailed and artistic images from text prompts. Perfect for artists, designers, and content creators looking for unique visuals.',
    category: 'Image Generation',
    subcategory: 'Art Creation',
    websiteUrl: 'https://www.midjourney.com',
    pricing: 'PAID',
    pricingDetails: 'Basic: $10/month, Standard: $30/month, Pro: $60/month',
    features: JSON.stringify(['Text-to-image', 'High resolution', 'Multiple styles', 'Commercial use', 'Discord integration']),
    tags: JSON.stringify(['image-generation', 'art', 'design', 'creative']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI pair programmer that suggests code and entire functions',
    longDescription: 'GitHub Copilot uses OpenAI Codex to suggest code and entire functions in real-time. It works with dozens of programming languages and integrates seamlessly into your IDE.',
    category: 'Code Assistant',
    subcategory: 'Development',
    websiteUrl: 'https://github.com/features/copilot',
    pricing: 'PAID',
    pricingDetails: 'Individual: $10/month, Business: $19/user/month',
    features: JSON.stringify(['Code completion', 'Multi-language support', 'IDE integration', 'Context-aware suggestions', 'Documentation generation']),
    tags: JSON.stringify(['coding', 'development', 'programming', 'automation']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Jasper AI',
    slug: 'jasper-ai',
    description: 'AI content platform for creating marketing copy, blog posts, and more',
    longDescription: 'Jasper AI is an advanced AI writing assistant designed for marketers and content creators. Generate high-quality content for blogs, ads, emails, and social media in seconds.',
    category: 'Content Generation',
    subcategory: 'Writing',
    websiteUrl: 'https://www.jasper.ai',
    pricing: 'PAID',
    pricingDetails: 'Creator: $49/month, Teams: $125/month',
    features: JSON.stringify(['Long-form content', 'SEO optimization', 'Multiple templates', 'Brand voice', 'Plagiarism checker']),
    tags: JSON.stringify(['writing', 'content', 'marketing', 'copywriting']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    description: 'Create realistic images and art from natural language descriptions',
    longDescription: 'DALL-E 3 by OpenAI generates high-quality images from text descriptions with improved accuracy and detail. Perfect for creating unique visuals for any project.',
    category: 'Image Generation',
    subcategory: 'AI Art',
    websiteUrl: 'https://openai.com/dall-e-3',
    pricing: 'PAID',
    pricingDetails: 'Pay per image or via ChatGPT Plus ($20/month)',
    features: JSON.stringify(['Text-to-image', 'High quality output', 'Multiple styles', 'Easy refinement', 'Commercial use']),
    tags: JSON.stringify(['image-generation', 'art', 'creative', 'design']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Runway ML',
    slug: 'runway-ml',
    description: 'AI-powered video editing and generation platform',
    longDescription: 'Runway ML offers AI tools for video editing, including background removal, motion tracking, and text-to-video generation. Used by filmmakers and content creators worldwide.',
    category: 'Video Creation',
    subcategory: 'Video Editing',
    websiteUrl: 'https://runwayml.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Standard: $12/month, Pro: $28/month',
    features: JSON.stringify(['Video generation', 'Background removal', 'Motion tracking', 'Green screen', 'AI effects']),
    tags: JSON.stringify(['video', 'editing', 'generation', 'effects']),
    isActive: true,
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    description: 'AI writing assistant for grammar, spelling, and style',
    longDescription: 'Grammarly uses AI to improve your writing with real-time grammar, spelling, punctuation, and style suggestions. Works everywhere you write online.',
    category: 'Content Generation',
    subcategory: 'Writing Assistant',
    websiteUrl: 'https://www.grammarly.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free version available, Premium: $12/month',
    features: JSON.stringify(['Grammar checking', 'Style suggestions', 'Tone detector', 'Plagiarism detection', 'Browser extension']),
    tags: JSON.stringify(['writing', 'grammar', 'editing', 'productivity']),
    isActive: true,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice generator with natural-sounding speech synthesis',
    longDescription: 'ElevenLabs provides cutting-edge AI voice generation technology for creating realistic voiceovers, audiobooks, and voice cloning with emotional range.',
    category: 'Voice & Audio',
    subcategory: 'Text-to-Speech',
    websiteUrl: 'https://elevenlabs.io',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free: 10k characters/month, Starter: $5/month, Creator: $22/month',
    features: JSON.stringify(['Voice cloning', 'Multiple languages', 'Emotional control', 'High quality audio', 'API access']),
    tags: JSON.stringify(['voice', 'audio', 'text-to-speech', 'voiceover']),
    isActive: true,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI-powered workspace for notes, docs, and project management',
    longDescription: 'Notion AI integrates advanced AI capabilities into Notion\'s workspace, helping you write, brainstorm, organize, and summarize content more efficiently.',
    category: 'Productivity',
    subcategory: 'Workspace',
    websiteUrl: 'https://www.notion.so/product/ai',
    pricing: 'PAID',
    pricingDetails: '$10/month add-on to Notion subscription',
    features: JSON.stringify(['Content generation', 'Summarization', 'Translation', 'Action items', 'Database queries']),
    tags: JSON.stringify(['productivity', 'notes', 'organization', 'workspace']),
    isActive: true,
  },
  {
    name: 'Copy.ai',
    slug: 'copy-ai',
    description: 'AI copywriting tool for marketing and sales content',
    longDescription: 'Copy.ai helps marketers and business owners create compelling copy for emails, social media, websites, and ads using advanced AI technology.',
    category: 'Content Generation',
    subcategory: 'Copywriting',
    websiteUrl: 'https://www.copy.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free: 2000 words/month, Pro: $49/month unlimited',
    features: JSON.stringify(['Ad copy', 'Email sequences', 'Blog posts', 'Social media', 'Product descriptions']),
    tags: JSON.stringify(['copywriting', 'marketing', 'content', 'sales']),
    isActive: true,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'AI-powered search engine with conversational answers',
    longDescription: 'Perplexity AI is a conversational search engine that provides accurate answers with citations. It combines the power of large language models with real-time web search.',
    category: 'Research',
    subcategory: 'Search',
    websiteUrl: 'https://www.perplexity.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free version available, Pro: $20/month',
    features: JSON.stringify(['AI-powered search', 'Citations', 'Follow-up questions', 'Mobile app', 'Research mode']),
    tags: JSON.stringify(['search', 'research', 'information', 'ai']),
    isActive: true,
  },
  {
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    description: 'Open-source AI image generation from text prompts',
    longDescription: 'Stable Diffusion is an open-source text-to-image model that can generate detailed images from text descriptions. Run it locally or use online platforms.',
    category: 'Image Generation',
    subcategory: 'Open Source',
    websiteUrl: 'https://stability.ai',
    pricing: 'FREE',
    pricingDetails: 'Open source and free to use',
    features: JSON.stringify(['Text-to-image', 'Image-to-image', 'Open source', 'Local installation', 'Custom training']),
    tags: JSON.stringify(['image-generation', 'open-source', 'ai-art']),
    isActive: true,
  },
  {
    name: 'Claude',
    slug: 'claude',
    description: 'AI assistant for analysis, research, and creative tasks',
    longDescription: 'Claude by Anthropic is an AI assistant focused on being helpful, harmless, and honest. Excellent for analysis, research, writing, coding, and creative work.',
    category: 'Content Generation',
    subcategory: 'AI Assistant',
    websiteUrl: 'https://claude.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Pro: $20/month',
    features: JSON.stringify(['Long context', 'Analysis', 'Research', 'Coding', 'Document processing']),
    tags: JSON.stringify(['ai-assistant', 'analysis', 'research', 'writing']),
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'Create AI-generated videos with virtual presenters',
    longDescription: 'Synthesia allows you to create professional videos with AI avatars in minutes. Perfect for training videos, marketing content, and presentations without filming.',
    category: 'Video Creation',
    subcategory: 'AI Avatars',
    websiteUrl: 'https://www.synthesia.io',
    pricing: 'PAID',
    pricingDetails: 'Personal: $30/month, Enterprise: Custom pricing',
    features: JSON.stringify(['AI avatars', 'Multiple languages', 'Custom avatars', 'Templates', 'Screen recording']),
    tags: JSON.stringify(['video', 'avatars', 'presentation', 'training']),
    isActive: true,
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    description: 'AI meeting transcription and note-taking assistant',
    longDescription: 'Otter.ai provides real-time transcription for meetings, interviews, and lectures. It automatically captures and shares notes, making meetings more productive.',
    category: 'Productivity',
    subcategory: 'Transcription',
    websiteUrl: 'https://otter.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Basic: Free, Pro: $10/month, Business: $20/month',
    features: JSON.stringify(['Real-time transcription', 'Meeting summaries', 'Speaker identification', 'Keyword search', 'Integrations']),
    tags: JSON.stringify(['transcription', 'meetings', 'notes', 'productivity']),
    isActive: true,
  },
  {
    name: 'Pictory',
    slug: 'pictory',
    description: 'Turn text content into engaging videos automatically',
    longDescription: 'Pictory uses AI to transform long-form content like blogs and scripts into short, branded videos. Perfect for social media and content marketing.',
    category: 'Video Creation',
    subcategory: 'Content Repurposing',
    websiteUrl: 'https://pictory.ai',
    pricing: 'PAID',
    pricingDetails: 'Standard: $23/month, Premium: $47/month',
    features: JSON.stringify(['Text-to-video', 'Auto-captions', 'Video highlights', 'Brand templates', 'Stock library']),
    tags: JSON.stringify(['video', 'content', 'social-media', 'automation']),
    isActive: true,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'All-in-one audio and video editing powered by AI',
    longDescription: 'Descript is a collaborative audio and video editor that transcribes your media and lets you edit it like a document. Includes overdub, filler word removal, and more.',
    category: 'Voice & Audio',
    subcategory: 'Audio Editing',
    websiteUrl: 'https://www.descript.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Creator: $12/month, Pro: $24/month',
    features: JSON.stringify(['Transcription', 'Audio editing', 'Video editing', 'Voice cloning', 'Collaboration']),
    tags: JSON.stringify(['audio', 'video', 'editing', 'transcription']),
    isActive: true,
  },
  {
    name: 'Canva AI',
    slug: 'canva-ai',
    description: 'Design platform with AI-powered features for graphics and content',
    longDescription: 'Canva\'s AI features include Magic Write, Magic Design, and background remover. Create professional designs, presentations, and social media content effortlessly.',
    category: 'Image Generation',
    subcategory: 'Graphic Design',
    websiteUrl: 'https://www.canva.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free version available, Pro: $12.99/month',
    features: JSON.stringify(['Templates', 'AI design', 'Background remover', 'Magic resize', 'Brand kit']),
    tags: JSON.stringify(['design', 'graphics', 'templates', 'social-media']),
    isActive: true,
  },
  {
    name: 'Murf AI',
    slug: 'murf-ai',
    description: 'AI voice generator for voiceovers and narration',
    longDescription: 'Murf AI provides studio-quality AI voices for podcasts, videos, presentations, and more. Choose from 120+ voices in 20+ languages.',
    category: 'Voice & Audio',
    subcategory: 'Voice Generation',
    websiteUrl: 'https://murf.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free trial, Basic: $19/month, Pro: $26/month',
    features: JSON.stringify(['120+ voices', '20+ languages', 'Voice customization', 'Background music', 'Team collaboration']),
    tags: JSON.stringify(['voice', 'voiceover', 'narration', 'audio']),
    isActive: true,
  },
  {
    name: 'QuillBot',
    slug: 'quillbot',
    description: 'AI paraphrasing and writing enhancement tool',
    longDescription: 'QuillBot helps you rewrite and enhance your writing with AI. Perfect for students, writers, and professionals looking to improve their text quality.',
    category: 'Content Generation',
    subcategory: 'Writing Enhancement',
    websiteUrl: 'https://quillbot.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free version available, Premium: $4.95/month',
    features: JSON.stringify(['Paraphrasing', 'Grammar checker', 'Summarizer', 'Citation generator', 'Multiple modes']),
    tags: JSON.stringify(['writing', 'paraphrasing', 'grammar', 'academic']),
    isActive: true,
  },
  {
    name: 'Beautiful.ai',
    slug: 'beautiful-ai',
    description: 'AI-powered presentation maker with smart templates',
    longDescription: 'Beautiful.ai uses AI to automatically format and design your presentations. Create stunning slides without design skills.',
    category: 'Productivity',
    subcategory: 'Presentations',
    websiteUrl: 'https://www.beautiful.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Pro: $12/month, Team: $40/user/month',
    features: JSON.stringify(['Smart templates', 'Auto-formatting', 'Team collaboration', 'Brand controls', 'Export options']),
    tags: JSON.stringify(['presentations', 'design', 'productivity', 'slides']),
    isActive: true,
  },
  {
    name: 'Scribe AI',
    slug: 'scribe-ai',
    description: 'Automatically create step-by-step guides and documentation',
    longDescription: 'Scribe captures your process and generates visual how-to guides automatically. Perfect for creating documentation, training materials, and SOPs.',
    category: 'Productivity',
    subcategory: 'Documentation',
    websiteUrl: 'https://scribehow.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free for basic use, Pro: $23/user/month',
    features: JSON.stringify(['Auto-capture', 'Visual guides', 'PDF export', 'Annotations', 'Team sharing']),
    tags: JSON.stringify(['documentation', 'guides', 'training', 'productivity']),
    isActive: true,
  },
  {
    name: 'Fireflies.ai',
    slug: 'fireflies-ai',
    description: 'AI meeting assistant that records and transcribes conversations',
    longDescription: 'Fireflies.ai joins your meetings to take notes, transcribe, and summarize. Integrates with major video conferencing platforms.',
    category: 'Productivity',
    subcategory: 'Meeting Assistant',
    websiteUrl: 'https://fireflies.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Pro: $10/month, Business: $19/month',
    features: JSON.stringify(['Auto-transcription', 'Meeting summaries', 'Action items', 'Searchable notes', 'CRM integration']),
    tags: JSON.stringify(['meetings', 'transcription', 'notes', 'productivity']),
    isActive: true,
  },
  {
    name: 'Tome',
    slug: 'tome',
    description: 'AI-powered storytelling and presentation platform',
    longDescription: 'Tome uses AI to help you create compelling narratives and presentations. Transform ideas into polished stories with AI-generated content and design.',
    category: 'Productivity',
    subcategory: 'Storytelling',
    websiteUrl: 'https://tome.app',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Pro: $10/month',
    features: JSON.stringify(['AI content generation', 'Smart design', 'Embeds', 'Collaboration', 'Templates']),
    tags: JSON.stringify(['presentations', 'storytelling', 'content', 'design']),
    isActive: true,
  },
  {
    name: 'Lumen5',
    slug: 'lumen5',
    description: 'Transform blog posts into engaging social videos',
    longDescription: 'Lumen5 uses AI to turn blog posts and articles into video content optimized for social media. No video editing experience required.',
    category: 'Video Creation',
    subcategory: 'Social Media',
    websiteUrl: 'https://lumen5.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Basic: Free, Starter: $19/month, Professional: $59/month',
    features: JSON.stringify(['Text-to-video', 'Social formats', 'Media library', 'Brand kit', 'Auto-captions']),
    tags: JSON.stringify(['video', 'social-media', 'content', 'marketing']),
    isActive: true,
  },
  {
    name: 'Writesonic',
    slug: 'writesonic',
    description: 'AI writer for articles, blogs, ads, and product descriptions',
    longDescription: 'Writesonic is an AI writing tool that helps create high-quality content for marketing, ecommerce, and content creation at scale.',
    category: 'Content Generation',
    subcategory: 'Content Writing',
    websiteUrl: 'https://writesonic.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free trial, Unlimited: $16/month',
    features: JSON.stringify(['Article writing', 'Ad copy', 'Product descriptions', 'SEO content', 'Multiple languages']),
    tags: JSON.stringify(['writing', 'content', 'marketing', 'seo']),
    isActive: true,
  },
  {
    name: 'Replit AI',
    slug: 'replit-ai',
    description: 'AI-powered code completion and generation in the browser',
    longDescription: 'Replit AI (formerly Ghostwriter) provides intelligent code suggestions and generation within Replit\'s collaborative browser IDE.',
    category: 'Code Assistant',
    subcategory: 'Web IDE',
    websiteUrl: 'https://replit.com',
    pricing: 'PAID',
    pricingDetails: 'Cycles-based or $10/month',
    features: JSON.stringify(['Code completion', 'Code generation', 'Code explanation', 'Multiple languages', 'Browser-based']),
    tags: JSON.stringify(['coding', 'development', 'ide', 'collaboration']),
    isActive: true,
  },
  {
    name: 'Mem',
    slug: 'mem',
    description: 'AI-powered note-taking with auto-organization',
    longDescription: 'Mem is a self-organizing workspace that uses AI to connect your notes, meetings, and ideas automatically. Never lose track of information again.',
    category: 'Productivity',
    subcategory: 'Note-Taking',
    websiteUrl: 'https://mem.ai',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free tier available, Pro: $10/month',
    features: JSON.stringify(['Auto-organization', 'AI summaries', 'Smart search', 'Meeting integration', 'Templates']),
    tags: JSON.stringify(['notes', 'organization', 'productivity', 'knowledge']),
    isActive: true,
  },
  {
    name: 'Wordtune',
    slug: 'wordtune',
    description: 'AI writing companion for rewriting and enhancing text',
    longDescription: 'Wordtune helps you rephrase sentences, find better words, and adjust your tone. Perfect for improving clarity and impact in your writing.',
    category: 'Content Generation',
    subcategory: 'Writing Assistant',
    websiteUrl: 'https://www.wordtune.com',
    pricing: 'FREEMIUM',
    pricingDetails: 'Free version available, Premium: $9.99/month',
    features: JSON.stringify(['Rewriting', 'Tone adjustment', 'Vocabulary enhancement', 'Browser extension', 'Multiple languages']),
    tags: JSON.stringify(['writing', 'rewriting', 'enhancement', 'productivity']),
    isActive: true,
  },
  {
    name: 'ResearchRabbit',
    slug: 'researchrabbit',
    description: 'AI-powered research discovery and literature mapping',
    longDescription: 'ResearchRabbit helps researchers discover papers, visualize connections, and stay updated on their topics of interest. The Spotify of research papers.',
    category: 'Research',
    subcategory: 'Academic',
    websiteUrl: 'https://researchrabbit.ai',
    pricing: 'FREE',
    pricingDetails: 'Free for all researchers',
    features: JSON.stringify(['Paper discovery', 'Citation mapping', 'Recommendations', 'Collections', 'Collaboration']),
    tags: JSON.stringify(['research', 'academic', 'papers', 'discovery']),
    isActive: true,
  },
];
