import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const realAITools = [
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    description: 'Advanced AI chatbot by OpenAI for conversations, writing, coding, and problem-solving with natural language understanding',
    category: 'Content Generation',
    websiteUrl: 'https://chat.openai.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'AI-powered image generation tool that creates stunning artwork from text descriptions',
    category: 'Image Generation',
    websiteUrl: 'https://www.midjourney.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'AI pair programmer that helps you write code faster with intelligent code completions',
    category: 'Code Assistant',
    websiteUrl: 'https://github.com/features/copilot',
    pricing: 'PAID',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Claude',
    slug: 'claude',
    description: 'Anthropic\'s AI assistant for analysis, writing, math, coding, and thoughtful conversation',
    category: 'Content Generation',
    websiteUrl: 'https://claude.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'DALL-E 3',
    slug: 'dalle-3',
    description: 'OpenAI\'s latest image generation model creating highly detailed images from text prompts',
    category: 'Image Generation',
    websiteUrl: 'https://openai.com/dall-e-3',
    pricing: 'PAID',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Jasper AI',
    slug: 'jasper-ai',
    description: 'AI content platform for marketing teams to create high-quality content at scale',
    category: 'Content Generation',
    websiteUrl: 'https://www.jasper.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Runway ML',
    slug: 'runway-ml',
    description: 'AI-powered video editing and generation platform with advanced creative tools',
    category: 'Video',
    websiteUrl: 'https://runwayml.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Grammarly',
    slug: 'grammarly',
    description: 'AI writing assistant that helps improve grammar, spelling, and writing style',
    category: 'Writing',
    websiteUrl: 'https://www.grammarly.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    description: 'AI voice generation platform creating realistic speech in multiple languages',
    category: 'Audio',
    websiteUrl: 'https://elevenlabs.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI-powered writing assistant integrated into Notion for summaries, brainstorming, and content creation',
    category: 'Productivity',
    websiteUrl: 'https://www.notion.so/product/ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Copy.ai',
    slug: 'copy-ai',
    description: 'AI copywriting tool for marketing content, social media posts, and product descriptions',
    category: 'Content Generation',
    websiteUrl: 'https://www.copy.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description: 'AI-powered search engine providing accurate answers with cited sources',
    category: 'Research',
    websiteUrl: 'https://www.perplexity.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    description: 'Open-source AI image generation model for creating detailed images from text',
    category: 'Image Generation',
    websiteUrl: 'https://stability.ai',
    pricing: 'FREE',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Synthesia',
    slug: 'synthesia',
    description: 'AI video generation platform creating professional videos with AI avatars',
    category: 'Video',
    websiteUrl: 'https://www.synthesia.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Otter.ai',
    slug: 'otter-ai',
    description: 'AI meeting assistant that records audio, transcribes, and generates meeting notes',
    category: 'Productivity',
    websiteUrl: 'https://otter.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Pictory',
    slug: 'pictory',
    description: 'AI-powered video creation tool turning text content into engaging videos',
    category: 'Video',
    websiteUrl: 'https://pictory.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'All-in-one audio and video editing with AI transcription and voice cloning',
    category: 'Audio',
    websiteUrl: 'https://www.descript.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Canva AI',
    slug: 'canva-ai',
    description: 'Graphic design platform with AI-powered design tools and magic features',
    category: 'Design',
    websiteUrl: 'https://www.canva.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Murf AI',
    slug: 'murf-ai',
    description: 'AI voice generator for creating realistic voiceovers in multiple languages',
    category: 'Audio',
    websiteUrl: 'https://murf.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'QuillBot',
    slug: 'quillbot',
    description: 'AI paraphrasing and writing enhancement tool for improving text clarity',
    category: 'Writing',
    websiteUrl: 'https://quillbot.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Beautiful.ai',
    slug: 'beautiful-ai',
    description: 'AI-powered presentation software that automatically designs slides',
    category: 'Productivity',
    websiteUrl: 'https://www.beautiful.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Scribe AI',
    slug: 'scribe-ai',
    description: 'AI tool that automatically creates step-by-step guides and documentation',
    category: 'Productivity',
    websiteUrl: 'https://scribehow.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Fireflies.ai',
    slug: 'fireflies-ai',
    description: 'AI meeting assistant that records, transcribes, and analyzes conversations',
    category: 'Productivity',
    websiteUrl: 'https://fireflies.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Tome',
    slug: 'tome',
    description: 'AI-powered storytelling platform for creating presentations and narratives',
    category: 'Productivity',
    websiteUrl: 'https://tome.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Lumen5',
    slug: 'lumen5',
    description: 'AI video creation platform turning blog posts and content into videos',
    category: 'Video',
    websiteUrl: 'https://lumen5.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Writesonic',
    slug: 'writesonic',
    description: 'AI writing tool for articles, blogs, ads, and marketing copy',
    category: 'Content Generation',
    websiteUrl: 'https://writesonic.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Replit AI',
    slug: 'replit-ai',
    description: 'AI-powered code completion and assistance within the Replit IDE',
    category: 'Code Assistant',
    websiteUrl: 'https://replit.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Mem',
    slug: 'mem',
    description: 'AI-powered note-taking app that organizes and surfaces information automatically',
    category: 'Productivity',
    websiteUrl: 'https://get.mem.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Wordtune',
    slug: 'wordtune',
    description: 'AI writing companion that helps rewrite and improve text clarity',
    category: 'Writing',
    websiteUrl: 'https://www.wordtune.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'ResearchRabbit',
    slug: 'researchrabbit',
    description: 'AI-powered research discovery tool for finding and organizing academic papers',
    category: 'Research',
    websiteUrl: 'https://www.researchrabbit.ai',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Simplified',
    slug: 'simplified',
    description: 'All-in-one design, video, and content creation platform powered by AI',
    category: 'Design',
    websiteUrl: 'https://simplified.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Krea AI',
    slug: 'krea-ai',
    description: 'Real-time AI image generation and enhancement tool for creative workflows',
    category: 'Image Generation',
    websiteUrl: 'https://krea.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Leonardo AI',
    slug: 'leonardo-ai',
    description: 'AI art generator for creating production-quality visual assets with consistency',
    category: 'Image Generation',
    websiteUrl: 'https://leonardo.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    description: 'AI-powered presentation and document creation tool with beautiful templates',
    category: 'Productivity',
    websiteUrl: 'https://gamma.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Anthropic Claude',
    slug: 'anthropic-claude',
    description: 'Constitutional AI assistant for safe, helpful conversations and content creation',
    category: 'Content Generation',
    websiteUrl: 'https://www.anthropic.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Pika Labs',
    slug: 'pika-labs',
    description: 'AI video generation platform creating videos from text and images',
    category: 'Video',
    websiteUrl: 'https://pika.art',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Suno AI',
    slug: 'suno-ai',
    description: 'AI music generation tool creating original songs from text descriptions',
    category: 'Audio',
    websiteUrl: 'https://suno.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Hugging Face',
    slug: 'hugging-face',
    description: 'Platform for building, training, and deploying machine learning models',
    category: 'Code Assistant',
    websiteUrl: 'https://huggingface.co',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Gemini',
    slug: 'gemini',
    description: 'Google\'s most capable AI model for text, code, images, and multimodal tasks',
    category: 'Content Generation',
    websiteUrl: 'https://gemini.google.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor built for pair programming with AI',
    category: 'Code Assistant',
    websiteUrl: 'https://cursor.sh',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Framer AI',
    slug: 'framer-ai',
    description: 'AI-powered website builder and design tool for creating responsive sites',
    category: 'Design',
    websiteUrl: 'https://www.framer.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Adobe Firefly',
    slug: 'adobe-firefly',
    description: 'Adobe\'s AI image and text effect generator integrated into Creative Cloud',
    category: 'Image Generation',
    websiteUrl: 'https://www.adobe.com/products/firefly.html',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Playground AI',
    slug: 'playground-ai',
    description: 'Free AI image creator with powerful editing and generation capabilities',
    category: 'Image Generation',
    websiteUrl: 'https://playgroundai.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Jenni AI',
    slug: 'jenni-ai',
    description: 'AI writing assistant for academic and research papers with citations',
    category: 'Writing',
    websiteUrl: 'https://jenni.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Anthropic',
    slug: 'anthropic',
    description: 'AI safety company developing reliable, interpretable AI systems',
    category: 'Research',
    websiteUrl: 'https://www.anthropic.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Rewind AI',
    slug: 'rewind-ai',
    description: 'Personal AI that records and makes searchable everything you\'ve seen or heard',
    category: 'Productivity',
    websiteUrl: 'https://www.rewind.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'HeyGen',
    slug: 'heygen',
    description: 'AI video platform for creating spokesperson videos with digital avatars',
    category: 'Video',
    websiteUrl: 'https://www.heygen.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Krisp',
    slug: 'krisp',
    description: 'AI noise cancellation for calls, meetings, and recordings',
    category: 'Audio',
    websiteUrl: 'https://krisp.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Looka',
    slug: 'looka',
    description: 'AI logo maker and brand identity platform for businesses',
    category: 'Design',
    websiteUrl: 'https://looka.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Tabnine',
    slug: 'tabnine',
    description: 'AI code completion tool supporting all major programming languages',
    category: 'Code Assistant',
    websiteUrl: 'https://www.tabnine.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Notion AI Writer',
    slug: 'notion-ai-writer',
    description: 'Integrated AI writing features within Notion workspace',
    category: 'Productivity',
    websiteUrl: 'https://www.notion.so',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Fliki',
    slug: 'fliki',
    description: 'Text to video and text to speech AI tool for content creators',
    category: 'Video',
    websiteUrl: 'https://fliki.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Speechify',
    slug: 'speechify',
    description: 'AI text-to-speech app for listening to documents, articles, and books',
    category: 'Audio',
    websiteUrl: 'https://speechify.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Cleaned',
    slug: 'cleaned',
    description: 'AI-powered image background removal tool for e-commerce and design',
    category: 'Image Generation',
    websiteUrl: 'https://cleaned.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Lex',
    slug: 'lex',
    description: 'AI-powered writing tool designed for creative and long-form content',
    category: 'Writing',
    websiteUrl: 'https://lex.page',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Compose AI',
    slug: 'compose-ai',
    description: 'Free Chrome extension that cuts writing time by 40% with AI autocompletion',
    category: 'Writing',
    websiteUrl: 'https://www.compose.ai',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Sudowrite',
    slug: 'sudowrite',
    description: 'AI writing partner for fiction authors and creative storytellers',
    category: 'Writing',
    websiteUrl: 'https://www.sudowrite.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Artbreeder',
    slug: 'artbreeder',
    description: 'Collaborative AI tool for creating and remixing images using genetic algorithms',
    category: 'Image Generation',
    websiteUrl: 'https://www.artbreeder.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Soundraw',
    slug: 'soundraw',
    description: 'AI music generator creating royalty-free music for content creators',
    category: 'Audio',
    websiteUrl: 'https://soundraw.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Zapier',
    slug: 'zapier',
    description: 'Automation platform connecting apps and services with AI-powered workflows',
    category: 'Productivity',
    websiteUrl: 'https://zapier.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Landbot',
    slug: 'landbot',
    description: 'No-code chatbot builder for creating conversational experiences',
    category: 'Productivity',
    websiteUrl: 'https://landbot.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Character.AI',
    slug: 'character-ai',
    description: 'AI platform for creating and chatting with AI characters',
    category: 'Content Generation',
    websiteUrl: 'https://character.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Replika',
    slug: 'replika',
    description: 'AI companion app for meaningful conversations and emotional support',
    category: 'Content Generation',
    websiteUrl: 'https://replika.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Bing AI',
    slug: 'bing-ai',
    description: 'Microsoft\'s AI-powered search engine with chat capabilities',
    category: 'Research',
    websiteUrl: 'https://www.bing.com/chat',
    pricing: 'FREE',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Bard',
    slug: 'bard',
    description: 'Google\'s experimental conversational AI service',
    category: 'Content Generation',
    websiteUrl: 'https://bard.google.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: true,
  },
  {
    name: 'Upscale.media',
    slug: 'upscale-media',
    description: 'AI image upscaler for enlarging images without quality loss',
    category: 'Image Generation',
    websiteUrl: 'https://upscale.media',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Remove.bg',
    slug: 'remove-bg',
    description: 'Automatic background removal tool using AI',
    category: 'Image Generation',
    websiteUrl: 'https://www.remove.bg',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'DeepL',
    slug: 'deepl',
    description: 'AI-powered translation service with superior accuracy',
    category: 'Writing',
    websiteUrl: 'https://www.deepl.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Rytr',
    slug: 'rytr',
    description: 'AI writing assistant for creating quality content in seconds',
    category: 'Content Generation',
    websiteUrl: 'https://rytr.me',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Craiyon',
    slug: 'craiyon',
    description: 'Free AI image generator formerly known as DALL-E mini',
    category: 'Image Generation',
    websiteUrl: 'https://www.craiyon.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'NightCafe',
    slug: 'nightcafe',
    description: 'AI art generator with multiple algorithms and styles',
    category: 'Image Generation',
    websiteUrl: 'https://creator.nightcafe.studio',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Podcastle',
    slug: 'podcastle',
    description: 'AI-powered podcast recording and editing platform',
    category: 'Audio',
    websiteUrl: 'https://podcastle.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Revoicer',
    slug: 'revoicer',
    description: 'AI voice-over platform with emotional text-to-speech',
    category: 'Audio',
    websiteUrl: 'https://revoicer.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Designs.ai',
    slug: 'designs-ai',
    description: 'Integrated AI creative platform for logos, videos, and mockups',
    category: 'Design',
    websiteUrl: 'https://designs.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Texti',
    slug: 'texti',
    description: 'AI writing assistant for quick content creation',
    category: 'Writing',
    websiteUrl: 'https://texti.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'AI Writer',
    slug: 'ai-writer',
    description: 'AI content generator for accurate, SEO-friendly articles',
    category: 'Content Generation',
    websiteUrl: 'https://ai-writer.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Beatoven.ai',
    slug: 'beatoven-ai',
    description: 'AI music generator for creating original soundtracks',
    category: 'Audio',
    websiteUrl: 'https://www.beatoven.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kaiber',
    slug: 'kaiber',
    description: 'AI video generation from images and text prompts',
    category: 'Video',
    websiteUrl: 'https://kaiber.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'D-ID',
    slug: 'd-id',
    description: 'AI video platform for creating talking avatars from photos',
    category: 'Video',
    websiteUrl: 'https://www.d-id.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Vizard',
    slug: 'vizard',
    description: 'AI video editor for repurposing long videos into clips',
    category: 'Video',
    websiteUrl: 'https://vizard.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Unscreen',
    slug: 'unscreen',
    description: 'Remove video backgrounds automatically with AI',
    category: 'Video',
    websiteUrl: 'https://www.unscreen.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Phrasee',
    slug: 'phrasee',
    description: 'AI-powered marketing language optimization',
    category: 'Content Generation',
    websiteUrl: 'https://phrasee.co',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Anyword',
    slug: 'anyword',
    description: 'AI copywriting platform for marketing content',
    category: 'Content Generation',
    websiteUrl: 'https://anyword.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Frase',
    slug: 'frase',
    description: 'AI content optimization and SEO writing tool',
    category: 'Content Generation',
    websiteUrl: 'https://www.frase.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Surfer SEO',
    slug: 'surfer-seo',
    description: 'AI-powered SEO optimization and content editor',
    category: 'Content Generation',
    websiteUrl: 'https://surferseo.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Heyday',
    slug: 'heyday',
    description: 'AI memory assistant that resurfaces content while browsing',
    category: 'Productivity',
    websiteUrl: 'https://heyday.xyz',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Coda AI',
    slug: 'coda-ai',
    description: 'All-in-one doc with AI-powered automation',
    category: 'Productivity',
    websiteUrl: 'https://coda.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Taskade',
    slug: 'taskade',
    description: 'AI-powered team collaboration and task management',
    category: 'Productivity',
    websiteUrl: 'https://www.taskade.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Motion',
    slug: 'motion',
    description: 'AI calendar that automatically plans your schedule',
    category: 'Productivity',
    websiteUrl: 'https://www.usemotion.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Reclaim AI',
    slug: 'reclaim-ai',
    description: 'Smart calendar app that finds time for your priorities',
    category: 'Productivity',
    websiteUrl: 'https://reclaim.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Superhuman',
    slug: 'superhuman',
    description: 'Fastest email experience with AI-powered features',
    category: 'Productivity',
    websiteUrl: 'https://superhuman.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Adept',
    slug: 'adept',
    description: 'AI teammate that helps with tasks in software tools',
    category: 'Productivity',
    websiteUrl: 'https://www.adept.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    description: 'Conversational search engine with source citations',
    category: 'Research',
    websiteUrl: 'https://www.perplexity.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Elicit',
    slug: 'elicit',
    description: 'AI research assistant for literature reviews',
    category: 'Research',
    websiteUrl: 'https://elicit.org',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Consensus',
    slug: 'consensus',
    description: 'AI search engine for scientific research papers',
    category: 'Research',
    websiteUrl: 'https://consensus.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Scholarcy',
    slug: 'scholarcy',
    description: 'AI-powered article summarizer for research',
    category: 'Research',
    websiteUrl: 'https://www.scholarcy.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Tome AI',
    slug: 'tome-ai',
    description: 'AI storytelling format for presentations',
    category: 'Productivity',
    websiteUrl: 'https://tome.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Presentations.AI',
    slug: 'presentations-ai',
    description: 'AI presentation maker with instant formatting',
    category: 'Productivity',
    websiteUrl: 'https://presentations.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Vondy',
    slug: 'vondy',
    description: 'AI platform with multiple creative tools and templates',
    category: 'Productivity',
    websiteUrl: 'https://vondy.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Lumai',
    slug: 'lumai',
    description: 'AI-powered video generation and editing platform',
    category: 'Video',
    websiteUrl: 'https://lumalabs.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Aimylogic',
    slug: 'aimylogic',
    description: 'No-code chatbot builder for businesses',
    category: 'Productivity',
    websiteUrl: 'https://aimylogic.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Mixo',
    slug: 'mixo',
    description: 'AI website builder that creates sites in seconds',
    category: 'Design',
    websiteUrl: 'https://mixo.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Playground',
    slug: 'playground',
    description: 'Browser-based code editor with AI assistance',
    category: 'Code Assistant',
    websiteUrl: 'https://playgroundai.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Lavender',
    slug: 'lavender',
    description: 'AI email assistant for sales professionals',
    category: 'Productivity',
    websiteUrl: 'https://lavender.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Slides AI',
    slug: 'slides-ai',
    description: 'Create presentation slides with AI in seconds',
    category: 'Productivity',
    websiteUrl: 'https://slidesai.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Moonbeam',
    slug: 'moonbeam',
    description: 'AI writing assistant for long-form content',
    category: 'Writing',
    websiteUrl: 'https://gomoonbeam.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Decktopus',
    slug: 'decktopus',
    description: 'AI-powered presentation generator',
    category: 'Productivity',
    websiteUrl: 'https://decktopus.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Copy Shark',
    slug: 'copy-shark',
    description: 'AI copywriting tool for ads and marketing',
    category: 'Content Generation',
    websiteUrl: 'https://copyshark.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Neural Love',
    slug: 'neural-love',
    description: 'AI art generator and image enhancer',
    category: 'Image Generation',
    websiteUrl: 'https://neural.love',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Magical',
    slug: 'magical',
    description: 'AI productivity tool for automating repetitive tasks',
    category: 'Productivity',
    websiteUrl: 'https://magical.so',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Phot.AI',
    slug: 'phot-ai',
    description: 'AI photo editing and enhancement platform',
    category: 'Image Generation',
    websiteUrl: 'https://phot.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Veed.io',
    slug: 'veed-io',
    description: 'Online video editing with AI features',
    category: 'Video',
    websiteUrl: 'https://www.veed.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Cleanvoice',
    slug: 'cleanvoice',
    description: 'AI audio editing for podcast cleanup',
    category: 'Audio',
    websiteUrl: 'https://cleanvoice.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Podium',
    slug: 'podium',
    description: 'AI-powered podcast show notes generator',
    category: 'Audio',
    websiteUrl: 'https://hello.podium.page',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Tome Pro',
    slug: 'tome-pro',
    description: 'AI storytelling and presentation tool',
    category: 'Productivity',
    websiteUrl: 'https://tome.app',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Galileo AI',
    slug: 'galileo-ai',
    description: 'AI-powered UI design tool',
    category: 'Design',
    websiteUrl: 'https://galileo.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Brandmark',
    slug: 'brandmark',
    description: 'AI logo maker for brands',
    category: 'Design',
    websiteUrl: 'https://brandmark.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Namelix',
    slug: 'namelix',
    description: 'AI business name generator',
    category: 'Productivity',
    websiteUrl: 'https://namelix.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Lensa AI',
    slug: 'lensa-ai',
    description: 'AI avatar and photo editor app',
    category: 'Image Generation',
    websiteUrl: 'https://prisma-ai.com/lensa',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Deep Dream Generator',
    slug: 'deep-dream-generator',
    description: 'AI art generation using deep learning',
    category: 'Image Generation',
    websiteUrl: 'https://deepdreamgenerator.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Supermeme',
    slug: 'supermeme',
    description: 'AI meme generator for social media',
    category: 'Content Generation',
    websiteUrl: 'https://supermeme.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Peech AI',
    slug: 'peech-ai',
    description: 'AI video editing platform for content teams',
    category: 'Video',
    websiteUrl: 'https://peech-ai.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Wisecut',
    slug: 'wisecut',
    description: 'Automatic video editor using AI',
    category: 'Video',
    websiteUrl: 'https://wisecut.video',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Steve AI',
    slug: 'steve-ai',
    description: 'AI video maker for social media',
    category: 'Video',
    websiteUrl: 'https://steve.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Mubert',
    slug: 'mubert',
    description: 'AI music generation for content creators',
    category: 'Audio',
    websiteUrl: 'https://mubert.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'AIVA',
    slug: 'aiva',
    description: 'AI music composition tool',
    category: 'Audio',
    websiteUrl: 'https://www.aiva.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  // Additional tools from screenshots batch 1-4
  {
    name: 'ThoughtfulGPT',
    slug: 'thoughtfulgpt',
    description: 'AI-powered thoughtful conversation and analysis tool',
    category: 'Content Generation',
    websiteUrl: 'https://thoughtfulgpt.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kroma',
    slug: 'kroma',
    description: 'AI color palette generation for designers',
    category: 'Design',
    websiteUrl: 'https://kroma.ai',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Memorable AI',
    slug: 'memorable-ai',
    description: 'AI-powered creative optimization and testing',
    category: 'Design',
    websiteUrl: 'https://memorable.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Reimagine XL',
    slug: 'reimagine-xl',
    description: 'AI image transformation and enhancement tool',
    category: 'Image Generation',
    websiteUrl: 'https://reimaginexl.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Spline AI',
    slug: 'spline-ai',
    description: 'AI-powered 3D design and modeling tool',
    category: 'Design',
    websiteUrl: 'https://spline.design',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Moemate',
    slug: 'moemate',
    description: 'AI companion and conversation platform',
    category: 'Content Generation',
    websiteUrl: 'https://moemate.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Sider AI',
    slug: 'sider-ai',
    description: 'AI sidebar assistant for browsing and productivity',
    category: 'Productivity',
    websiteUrl: 'https://sider.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Merlin AI',
    slug: 'merlin-ai',
    description: 'AI assistant browser extension for productivity',
    category: 'Productivity',
    websiteUrl: 'https://merlin.foyer.work',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kling AI',
    slug: 'kling-ai',
    description: 'AI video generation and editing platform',
    category: 'Video',
    websiteUrl: 'https://kling.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Grok AI',
    slug: 'grok-ai',
    description: 'X\'s AI assistant with real-time knowledge',
    category: 'Content Generation',
    websiteUrl: 'https://grok.x.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Hix AI',
    slug: 'hix-ai',
    description: 'AI writing assistant and content generator',
    category: 'Writing',
    websiteUrl: 'https://hix.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Rask AI',
    slug: 'rask-ai',
    description: 'AI video localization and dubbing platform',
    category: 'Video',
    websiteUrl: 'https://rask.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Cohesive AI',
    slug: 'cohesive-ai',
    description: 'AI content creation and collaboration platform',
    category: 'Content Generation',
    websiteUrl: 'https://cohesive.so',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Ideogram',
    slug: 'ideogram',
    description: 'AI text-to-image generation with typography',
    category: 'Image Generation',
    websiteUrl: 'https://ideogram.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Caktus AI',
    slug: 'caktus-ai',
    description: 'AI learning and homework assistance platform',
    category: 'Productivity',
    websiteUrl: 'https://caktus.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Monica AI',
    slug: 'monica-ai',
    description: 'AI assistant browser extension with ChatGPT',
    category: 'Productivity',
    websiteUrl: 'https://monica.im',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Promptbase',
    slug: 'promptbase',
    description: 'Marketplace for buying and selling AI prompts',
    category: 'Productivity',
    websiteUrl: 'https://promptbase.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Poe',
    slug: 'poe',
    description: 'Platform for accessing multiple AI chatbots',
    category: 'Content Generation',
    websiteUrl: 'https://poe.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Resume Worded',
    slug: 'resume-worded',
    description: 'AI resume and LinkedIn profile optimization',
    category: 'Writing',
    websiteUrl: 'https://resumeworded.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Phind',
    slug: 'phind',
    description: 'AI search engine for developers',
    category: 'Code Assistant',
    websiteUrl: 'https://www.phind.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Soundful',
    slug: 'soundful',
    description: 'AI music generator for creators',
    category: 'Audio',
    websiteUrl: 'https://soundful.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Codeium',
    slug: 'codeium',
    description: 'Free AI code completion and chat',
    category: 'Code Assistant',
    websiteUrl: 'https://codeium.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'ProWritingAid',
    slug: 'prowritingaid',
    description: 'AI writing assistant and grammar checker',
    category: 'Writing',
    websiteUrl: 'https://prowritingaid.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Clearscope',
    slug: 'clearscope',
    description: 'AI content optimization for SEO',
    category: 'Writing',
    websiteUrl: 'https://www.clearscope.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'MarketMuse',
    slug: 'marketmuse',
    description: 'AI content planning and optimization',
    category: 'Writing',
    websiteUrl: 'https://www.marketmuse.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Writesonic Photosonic',
    slug: 'photosonic',
    description: 'AI art generator from Writesonic',
    category: 'Image Generation',
    websiteUrl: 'https://photosonic.writesonic.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Starryai',
    slug: 'starryai',
    description: 'AI art generator app',
    category: 'Image Generation',
    websiteUrl: 'https://starryai.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Dream by WOMBO',
    slug: 'dream-by-wombo',
    description: 'AI-powered art generator',
    category: 'Image Generation',
    websiteUrl: 'https://dream.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Pixlr AI',
    slug: 'pixlr-ai',
    description: 'AI photo editing and generation',
    category: 'Image Generation',
    websiteUrl: 'https://pixlr.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Fotor AI',
    slug: 'fotor-ai',
    description: 'AI photo editor and design tool',
    category: 'Image Generation',
    websiteUrl: 'https://www.fotor.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Removal AI',
    slug: 'removal-ai',
    description: 'AI background removal tool',
    category: 'Image Generation',
    websiteUrl: 'https://removal.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Cleanup Pictures',
    slug: 'cleanup-pictures',
    description: 'AI object removal from photos',
    category: 'Image Generation',
    websiteUrl: 'https://cleanup.pictures',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Topaz Labs',
    slug: 'topaz-labs',
    description: 'AI photo enhancement and upscaling',
    category: 'Image Generation',
    websiteUrl: 'https://www.topazlabs.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Let\'s Enhance',
    slug: 'lets-enhance',
    description: 'AI image upscaling and enhancement',
    category: 'Image Generation',
    websiteUrl: 'https://letsenhance.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Upscayl',
    slug: 'upscayl',
    description: 'Free AI image upscaler',
    category: 'Image Generation',
    websiteUrl: 'https://upscayl.github.io',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Gigapixel AI',
    slug: 'gigapixel-ai',
    description: 'AI image upscaling by Topaz Labs',
    category: 'Image Generation',
    websiteUrl: 'https://www.topazlabs.com/gigapixel-ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Clipdrop',
    slug: 'clipdrop',
    description: 'AI-powered image editing tools',
    category: 'Image Generation',
    websiteUrl: 'https://clipdrop.co',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Cutout Pro',
    slug: 'cutout-pro',
    description: 'AI visual design and photo editing',
    category: 'Image Generation',
    websiteUrl: 'https://www.cutout.pro',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Mokker AI',
    slug: 'mokker-ai',
    description: 'AI product photography',
    category: 'Image Generation',
    websiteUrl: 'https://mokker.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Pebblely',
    slug: 'pebblely',
    description: 'AI product photography backgrounds',
    category: 'Image Generation',
    websiteUrl: 'https://pebblely.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'PhotoRoom',
    slug: 'photoroom',
    description: 'AI background remover and photo editor',
    category: 'Image Generation',
    websiteUrl: 'https://www.photoroom.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Uizard',
    slug: 'uizard',
    description: 'AI UI/UX design tool',
    category: 'Design',
    websiteUrl: 'https://uizard.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Visily',
    slug: 'visily',
    description: 'AI wireframe and design tool',
    category: 'Design',
    websiteUrl: 'https://www.visily.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Magician',
    slug: 'magician',
    description: 'AI design assistant for Figma',
    category: 'Design',
    websiteUrl: 'https://magician.design',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Khroma',
    slug: 'khroma',
    description: 'AI color palette generator',
    category: 'Design',
    websiteUrl: 'https://www.khroma.co',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Coolors AI',
    slug: 'coolors-ai',
    description: 'AI color scheme generator',
    category: 'Design',
    websiteUrl: 'https://coolors.co',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Palette FM',
    slug: 'palette-fm',
    description: 'AI colorization for black and white photos',
    category: 'Image Generation',
    websiteUrl: 'https://palette.fm',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Colormind',
    slug: 'colormind',
    description: 'AI color scheme generator',
    category: 'Design',
    websiteUrl: 'http://colormind.io',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Fontjoy',
    slug: 'fontjoy',
    description: 'AI font pairing generator',
    category: 'Design',
    websiteUrl: 'https://fontjoy.com',
    pricing: 'FREE',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Designs AI Video',
    slug: 'designs-ai-video',
    description: 'AI video maker',
    category: 'Video',
    websiteUrl: 'https://designs.ai/videomaker',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'InVideo AI',
    slug: 'invideo-ai',
    description: 'AI video creation and editing',
    category: 'Video',
    websiteUrl: 'https://invideo.io',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Animoto',
    slug: 'animoto',
    description: 'AI video maker for marketing',
    category: 'Video',
    websiteUrl: 'https://animoto.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Elai IO',
    slug: 'elai-io',
    description: 'AI video generation from text',
    category: 'Video',
    websiteUrl: 'https://elai.io',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Colossyan',
    slug: 'colossyan',
    description: 'AI video creator with AI actors',
    category: 'Video',
    websiteUrl: 'https://www.colossyan.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Hourone AI',
    slug: 'hourone-ai',
    description: 'AI video generation with virtual humans',
    category: 'Video',
    websiteUrl: 'https://hourone.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Bhuman',
    slug: 'bhuman',
    description: 'AI personalized video generation',
    category: 'Video',
    websiteUrl: 'https://www.bhuman.ai',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Vidyo AI',
    slug: 'vidyo-ai',
    description: 'AI video repurposing for social media',
    category: 'Video',
    websiteUrl: 'https://vidyo.ai',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'OpusClip',
    slug: 'opusclip',
    description: 'AI video clipping for short-form content',
    category: 'Video',
    websiteUrl: 'https://www.opus.pro',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Kapwing AI',
    slug: 'kapwing-ai',
    description: 'AI video editing and content creation',
    category: 'Video',
    websiteUrl: 'https://www.kapwing.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Wave Video',
    slug: 'wave-video',
    description: 'AI video creation and editing',
    category: 'Video',
    websiteUrl: 'https://wave.video',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Clipchamp',
    slug: 'clipchamp',
    description: 'Microsoft\'s AI video editor',
    category: 'Video',
    websiteUrl: 'https://clipchamp.com',
    pricing: 'FREEMIUM',
    isActive: true,
    isFeatured: false,
  },
  {
    name: 'Zubtitle',
    slug: 'zubtitle',
    description: 'AI auto-captioning for videos',
    category: 'Video',
    websiteUrl: 'https://zubtitle.com',
    pricing: 'PAID',
    isActive: true,
    isFeatured: false,
  },
];

async function main() {
  console.log('🌱 Starting database seed...');

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@aiworkspace.com' },
    update: {},
    create: {
      email: 'admin@aiworkspace.com',
      name: 'Admin User',
      password: hashedPassword,
      role: 'ADMIN',
    },
  });

  console.log('✅ Admin user created');

  // Create categories
  const categories = [
    { name: 'Content Generation', slug: 'content-generation', description: 'AI tools for writing, copywriting, and content creation' },
    { name: 'Image Generation', slug: 'image-generation', description: 'AI-powered image creation and editing tools' },
    { name: 'Video', slug: 'video', description: 'AI video generation, editing, and production tools' },
    { name: 'Code Assistant', slug: 'code-assistant', description: 'AI coding assistants and development tools' },
    { name: 'Audio', slug: 'audio', description: 'AI voice generation, transcription, and audio tools' },
    { name: 'Writing', slug: 'writing', description: 'AI writing enhancement and grammar tools' },
    { name: 'Productivity', slug: 'productivity', description: 'AI tools for productivity and workflow optimization' },
    { name: 'Research', slug: 'research', description: 'AI-powered research and information discovery tools' },
    { name: 'Design', slug: 'design', description: 'AI design and creative tools' },
  ];

  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: {},
      create: category,
    });
  }

  console.log('✅ Categories created');

  // Delete existing tools and submissions
  await prisma.workspaceTool.deleteMany({});
  await prisma.featureRequest.deleteMany({});
  await prisma.toolUpdateRequest.deleteMany({});
  await prisma.advertisingRequest.deleteMany({});
  await prisma.tool.deleteMany({});

  console.log('✅ Cleared old tools');

  // Create real AI tools
  for (const tool of realAITools) {
    await prisma.tool.create({
      data: tool,
    });
  }

  console.log(`✅ Created ${realAITools.length} real AI tools`);

  // Create a workspace for admin
  const workspace = await prisma.workspace.create({
    data: {
      name: 'My AI Workspace',
      userId: admin.id,
    },
  });

  // Add some featured tools to admin's workspace
  const featuredTools = await prisma.tool.findMany({
    where: { isFeatured: true },
    take: 6,
  });

  for (let i = 0; i < featuredTools.length; i++) {
    await prisma.workspaceTool.create({
      data: {
        workspaceId: workspace.id,
        toolId: featuredTools[i].id,
        position: i,
      },
    });
  }

  console.log('✅ Created admin workspace with featured tools');

  console.log('🎉 Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
